const express = require('express');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
const morgan = require('morgan');
const bcrypt = require('bcryptjs');
const { stringify } = require('csv-stringify/sync');
const { z } = require('zod');
const { db, todayBounds, money, makeBillNumber } = require('./db');
const { attachUser, requireAuth, requireRole, login, setSessionCookie, clearSessionCookie } = require('./auth');

const app = express();
app.set('view engine', 'ejs');
app.set('views', `${process.cwd()}/views`);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(morgan('dev'));
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
app.use(express.static('public'));
app.use(attachUser);

const PORT = process.env.PORT || 3000;
const notice = (req) => req.query.ok ? { type:'success', message:req.query.ok } : req.query.err ? { type:'error', message:req.query.err } : null;
const esc = (s='') => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(req, res, view, data={}) {
  res.render(view, { ...data, user:req.user, path:req.path, notice:notice(req), money }, (err, body) => {
    if (err) throw err;
    res.render('layout', { title:data.title || 'Dashboard', body, user:req.user, path:req.path, notice:notice(req), money });
  });
}
const redirectWith = (res, path, key, msg) => res.redirect(`${path}?${key}=${encodeURIComponent(msg)}`);
const number = (v) => Number(v || 0);
const int = (v) => Math.trunc(Number(v || 0));
const dateRange = (q) => {
  const today = new Date().toISOString().slice(0,10);
  const fromDate = q.from || today, toDate = q.to || today;
  return { fromDate, toDate, from:`${fromDate} 00:00:00`, to:`${toDate} 23:59:59` };
};
function itemRows(activeOnly=false){ return db.prepare(`SELECT i.*, inv.mainFridgeQty, inv.secondFridgeQty FROM items i JOIN inventory inv ON inv.itemId=i.id ${activeOnly?'WHERE i.active=1 AND i.hidden=0':''} ORDER BY i.name`).all(); }
function todaySummary(managerId){
  const {from,to}=todayBounds();
  return db.prepare(`SELECT COALESCE(SUM(s.totalAmount),0) total, COALESCE(SUM(s.cashAmount),0) cash, COALESCE(SUM(s.onlineAmount),0) online, COALESCE(SUM(si.quantity),0) pieces FROM sales s LEFT JOIN sale_items si ON si.saleId=s.id WHERE s.managerId=? AND s.createdAt BETWEEN ? AND ?`).get(managerId, from, to);
}
function returnableLines(managerId){
  const {from,to}=todayBounds();
  return db.prepare(`SELECT si.*, s.billNumber, s.managerId, i.name, i.itemCode, COALESCE((SELECT SUM(ABS(r.quantity)) FROM sale_items r WHERE r.originalSaleItemId=si.id),0) returnedQty FROM sale_items si JOIN sales s ON s.id=si.saleId JOIN items i ON i.id=si.itemId WHERE s.type='sale' AND s.managerId=? AND s.createdAt BETWEEN ? AND ? ORDER BY s.createdAt DESC`).all(managerId, from, to).filter(r => r.quantity - r.returnedQty > 0);
}
function reports(range){
  const rows = db.prepare(`SELECT s.*, u.name managerName, si.id saleItemId, si.quantity, si.mrp, si.isFree, si.lineTotal, si.originalSaleItemId, i.itemCode, i.name itemName FROM sales s JOIN users u ON u.id=s.managerId JOIN sale_items si ON si.saleId=s.id JOIN items i ON i.id=si.itemId WHERE s.createdAt BETWEEN ? AND ? ORDER BY s.createdAt DESC`).all(range.from, range.to);
  const gross = rows.filter(r=>r.type==='sale').reduce((a,r)=>a+r.lineTotal,0);
  const returns = rows.filter(r=>r.type==='return').reduce((a,r)=>a+Math.abs(r.lineTotal),0);
  const pieces = rows.reduce((a,r)=>a+r.quantity,0);
  const cash = [...new Map(rows.map(r=>[r.id,r])).values()].reduce((a,r)=>a+r.cashAmount,0);
  const online = [...new Map(rows.map(r=>[r.id,r])).values()].reduce((a,r)=>a+r.onlineAmount,0);
  return { rows, totals:{gross, returns, net:gross-returns, pieces, cash, online} };
}

app.get('/', (req,res)=> res.redirect(req.user ? (req.user.role==='owner'?'/owner':'/manager') : '/login'));
app.get('/login', (req,res)=> req.user ? res.redirect(req.user.role==='owner'?'/owner':'/manager') : render(req,res,'login',{title:'Login', error:req.query.err, next:req.query.next}));
app.post('/login', (req,res)=>{ const user = login(req.body.email, req.body.password); if(!user) return res.redirect('/login?err=Invalid%20email%20or%20password'); setSessionCookie(res,user); res.redirect(req.body.next || (user.role==='owner'?'/owner':'/manager')); });
app.post('/logout', (req,res)=>{ clearSessionCookie(res); res.redirect('/login'); });
app.get('/health', (req,res)=>{ try { db.prepare('SELECT COUNT(*) count FROM users').get(); res.json({ok:true,database:'reachable'}); } catch(e){ res.status(503).json({ok:false,error:'Database is not reachable'}); } });

app.get('/owner', requireRole('owner'), (req,res)=>{
  const {from,to}=todayBounds();
  const summary = db.prepare(`SELECT COALESCE(SUM(totalAmount),0) total,COALESCE(SUM(cashAmount),0) cash,COALESCE(SUM(onlineAmount),0) online FROM sales WHERE createdAt BETWEEN ? AND ?`).get(from,to);
  const pieces = db.prepare(`SELECT COALESCE(SUM(quantity),0) pieces FROM sale_items si JOIN sales s ON s.id=si.saleId WHERE s.createdAt BETWEEN ? AND ?`).get(from,to).pieces;
  const inventory = itemRows(true);
  const invValue = inventory.reduce((a,i)=>a+(i.mainFridgeQty+i.secondFridgeQty)*i.mrp,0);
  const main = inventory.reduce((a,i)=>a+i.mainFridgeQty,0), second=inventory.reduce((a,i)=>a+i.secondFridgeQty,0), low=inventory.filter(i=>i.mainFridgeQty<=i.lowStockThreshold).length;
  const stats=[['Today’s total sales amount',`₹${money(summary.total)}`],['Today’s total pieces sold',pieces],['Today’s cash collection total',`₹${money(summary.cash)}`],['Today’s online payment total',`₹${money(summary.online)}`],['Current total inventory value',`₹${money(invValue)}`],['Main fridge stock total',main],['Second fridge stock total',second],['Low-stock item count',low]].map(([label,value])=>({label,value}));
  const trend = [...Array(7)].map((_,idx)=>{ const d=new Date(); d.setDate(d.getDate()-6+idx); const day=d.toISOString().slice(0,10); const r=db.prepare(`SELECT COALESCE(SUM(totalAmount),0) amount FROM sales WHERE type='sale' AND createdAt BETWEEN ? AND ?`).get(`${day} 00:00:00`,`${day} 23:59:59`); return {day, amount:r.amount}; });
  const topItems = db.prepare(`SELECT i.name, SUM(si.quantity) qty, SUM(si.lineTotal) amount FROM sale_items si JOIN sales s ON s.id=si.saleId JOIN items i ON i.id=si.itemId WHERE s.createdAt BETWEEN ? AND ? GROUP BY i.id ORDER BY qty DESC LIMIT 5`).all(from,to);
  const managers = db.prepare(`SELECT u.name, COALESCE(SUM(s.totalAmount),0) total, COALESCE(SUM(s.cashAmount),0) cash, COALESCE(SUM(s.onlineAmount),0) online, COALESCE(SUM(si.quantity),0) pieces FROM users u LEFT JOIN sales s ON s.managerId=u.id AND s.createdAt BETWEEN ? AND ? LEFT JOIN sale_items si ON si.saleId=s.id WHERE u.role='manager' GROUP BY u.id`).all(from,to);
  const movements = db.prepare(`SELECT sm.*, i.name FROM stock_movements sm JOIN items i ON i.id=sm.itemId ORDER BY sm.createdAt DESC LIMIT 8`).all();
  render(req,res,'dashboard',{title:'Owner Dashboard',stats,summary,trend,topItems,inventory,managers,movements});
});

app.get('/owner/items', requireRole('owner'), (req,res)=>{
 const rows=itemRows(false); const form=`<h2>Add / edit kulfi item</h2><form method="post" action="/owner/items" class="form-grid"><label>Item ID<input name="itemCode" required></label><label>Name<input name="name" required></label><label>MRP<input name="mrp" type="number" min="1" step="0.01" required></label><label>Profit %<input name="profitPercentage" type="number" min="0" step="0.01"></label><label>Pieces / box<input name="piecesPerBox" type="number" min="1" required></label><label>Low stock threshold<input name="lowStockThreshold" type="number" min="0" required></label><button class="primary">Save item</button></form>`;
 const table=`<table><thead><tr><th>ID</th><th>Name</th><th>MRP</th><th>Box</th><th>Low</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.itemCode)}</td><td>${esc(r.name)}</td><td>₹${money(r.mrp)}</td><td>${r.piecesPerBox}</td><td>${r.lowStockThreshold}</td><td><span class="badge ${r.active?'ok':'danger'}">${r.active?'Active':'Inactive'}</span> ${r.hidden?'<span class="badge warn">Hidden</span>':''}</td><td><form class="actions" method="post" action="/owner/items/${r.id}/toggle"><button name="field" value="active" class="btn secondary">${r.active?'Deactivate':'Activate'}</button><button name="field" value="hidden" class="btn secondary">${r.hidden?'Unhide':'Hide'}</button></form></td></tr>`).join('')}</tbody></table>`;
 render(req,res,'table-page',{title:'Item Catalog Management',form,table});
});
app.post('/owner/items', requireRole('owner'), (req,res)=>{ try{ const b=z.object({itemCode:z.string().min(1),name:z.string().min(1),mrp:z.coerce.number().positive(),profitPercentage:z.coerce.number().min(0).default(0),piecesPerBox:z.coerce.number().int().positive(),lowStockThreshold:z.coerce.number().int().min(0)}).parse(req.body); db.transaction(()=>{ const id=db.prepare(`INSERT INTO items (itemCode,name,mrp,profitPercentage,piecesPerBox,lowStockThreshold) VALUES (?,?,?,?,?,?)`).run(b.itemCode,b.name,b.mrp,b.profitPercentage,b.piecesPerBox,b.lowStockThreshold).lastInsertRowid; db.prepare('INSERT INTO inventory (itemId) VALUES (?)').run(id); })(); redirectWith(res,'/owner/items','ok','Item saved'); } catch(e){ redirectWith(res,'/owner/items','err', e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Duplicate item ID or name is not allowed':'Invalid item data'); }});
app.post('/owner/items/:id/toggle', requireRole('owner'), (req,res)=>{ const field=req.body.field==='hidden'?'hidden':'active'; db.prepare(`UPDATE items SET ${field}=CASE ${field} WHEN 1 THEN 0 ELSE 1 END, updatedAt=CURRENT_TIMESTAMP WHERE id=?`).run(req.params.id); redirectWith(res,'/owner/items','ok','Item updated'); });

app.get('/owner/inventory', requireRole('owner'), (req,res)=>{ const rows=itemRows(true); const form=`<h2>Bulk stock balances</h2><form method="post" action="/owner/inventory"><div class="table-wrap"><table><thead><tr><th>Item</th><th>Main Fridge</th><th>Second Fridge</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}<input type="hidden" name="itemId" value="${r.id}"></td><td><input name="main_${r.id}" type="number" min="0" value="${r.mainFridgeQty}"></td><td><input name="second_${r.id}" type="number" min="0" value="${r.secondFridgeQty}"></td></tr>`).join('')}</tbody></table></div><button class="primary">Save balances</button></form>`; const table=`<table><thead><tr><th>Item</th><th>Main</th><th>Second</th><th>Total Value</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.mainFridgeQty}</td><td>${r.secondFridgeQty}</td><td>₹${money((r.mainFridgeQty+r.secondFridgeQty)*r.mrp)}</td><td><span class="badge ${r.mainFridgeQty<=r.lowStockThreshold?'danger':'ok'}">${r.mainFridgeQty<=r.lowStockThreshold?'Low stock':'OK'}</span></td></tr>`).join('')}</tbody></table>`; render(req,res,'table-page',{title:'Stock / Inventory Management',form,table}); });
app.post('/owner/inventory', requireRole('owner'), (req,res)=>{ db.transaction(()=>{ (Array.isArray(req.body.itemId)?req.body.itemId:[req.body.itemId]).forEach(id=>{ const before=db.prepare('SELECT * FROM inventory WHERE itemId=?').get(id); const main=int(req.body[`main_${id}`]), second=int(req.body[`second_${id}`]); if(main<0||second<0) throw new Error('Never allow negative stock'); db.prepare('UPDATE inventory SET mainFridgeQty=?, secondFridgeQty=?, updatedAt=CURRENT_TIMESTAMP WHERE itemId=?').run(main,second,id); db.prepare(`INSERT INTO stock_movements (itemId,movementType,quantityPieces,quantityBoxes,sourceLocation,destinationLocation,notes,createdBy) VALUES (?,?,?,?,?,?,?,?)`).run(id,'stock_adjustment',(main-before.mainFridgeQty)+(second-before.secondFridgeQty),0,'inventory_count','inventory_count','Owner bulk balance update',req.user.id); }); })(); redirectWith(res,'/owner/inventory','ok','Stock balances saved'); });

app.get('/owner/movements', requireRole('owner'), (req,res)=>{ const items=itemRows(true); const f=req.query; const where=[], params=[]; if(f.type){where.push('sm.movementType=?');params.push(f.type)} if(f.itemId){where.push('sm.itemId=?');params.push(f.itemId)} if(f.from){where.push('sm.createdAt>=?');params.push(`${f.from} 00:00:00`)} if(f.to){where.push('sm.createdAt<=?');params.push(`${f.to} 23:59:59`)} const rows=db.prepare(`SELECT sm.*, i.name, i.piecesPerBox, u.name createdByName FROM stock_movements sm JOIN items i ON i.id=sm.itemId JOIN users u ON u.id=sm.createdBy ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY sm.createdAt DESC LIMIT 300`).all(...params); const form=`<h2>Record stock movement</h2><form method="post" action="/owner/movements" class="form-grid"><label>Item<select name="itemId">${items.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`)}</select></label><label>Movement<select name="movementType"><option value="vendor_stock_in">Vendor stock-in</option><option value="stock_adjustment">Stock adjustment</option></select></label><label>Location<select name="location"><option value="main_fridge">Main Fridge</option><option value="second_fridge">Second Fridge</option></select></label><label>Boxes<input name="quantityBoxes" type="number" min="0" step="0.01"></label><label>Pieces<input name="quantityPieces" type="number" step="1"></label><label>Notes<input name="notes"></label><button class="primary">Record movement</button></form>`; const intro=`<form class="card form-grid" method="get"><label>Type<select name="type"><option value="">All</option>${['vendor_stock_in','transfer_second_to_main','stock_adjustment','return_movement','pos_sale'].map(t=>`<option ${f.type===t?'selected':''} value="${t}">${t.replaceAll('_',' ')}</option>`)}</select></label><label>Item<select name="itemId"><option value="">All</option>${items.map(i=>`<option ${String(f.itemId)===String(i.id)?'selected':''} value="${i.id}">${esc(i.name)}</option>`)}</select></label><label>From<input type="date" name="from" value="${esc(f.from||'')}"></label><label>To<input type="date" name="to" value="${esc(f.to||'')}"></label><button class="primary">Filter</button></form>`; const table=`<table><thead><tr><th>ID</th><th>Item</th><th>Type</th><th>Boxes</th><th>Pieces</th><th>From</th><th>To</th><th>By</th><th>Date</th><th>Notes</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id}</td><td>${esc(r.name)}</td><td>${r.movementType.replaceAll('_',' ')}</td><td>${r.quantityBoxes}</td><td>${r.quantityPieces}</td><td>${esc(r.sourceLocation||'')}</td><td>${esc(r.destinationLocation||'')}</td><td>${esc(r.createdByName)}</td><td>${r.createdAt}</td><td>${esc(r.notes||'')}</td></tr>`).join('')}</tbody></table>`; render(req,res,'table-page',{title:'Stock Movement Ledger',intro,form,table}); });
app.post('/owner/movements', requireRole('owner'), (req,res)=>{ try{ db.transaction(()=>{ const item=db.prepare('SELECT * FROM items JOIN inventory ON inventory.itemId=items.id WHERE items.id=?').get(req.body.itemId); let qty=int(req.body.quantityPieces); if(!qty) qty=Math.round(number(req.body.quantityBoxes)*item.piecesPerBox); if(!qty) throw new Error('Enter movement quantity'); const loc=req.body.location==='second_fridge'?'secondFridgeQty':'mainFridgeQty'; const next=item[loc]+qty; if(next<0) throw new Error('Never allow negative stock'); db.prepare(`UPDATE inventory SET ${loc}=?, updatedAt=CURRENT_TIMESTAMP WHERE itemId=?`).run(next,item.id); db.prepare(`INSERT INTO stock_movements (itemId,movementType,quantityPieces,quantityBoxes,sourceLocation,destinationLocation,notes,createdBy) VALUES (?,?,?,?,?,?,?,?)`).run(item.id,req.body.movementType,qty,number(req.body.quantityBoxes),qty>0?'vendor/adjustment':req.body.location,qty>0?req.body.location:'adjustment',req.body.notes,req.user.id); })(); redirectWith(res,'/owner/movements','ok','Stock movement recorded'); } catch(e){ redirectWith(res,'/owner/movements','err',e.message); }});

app.get('/owner/users', requireRole('owner'), (req,res)=>{ const rows=db.prepare('SELECT id,name,email,role,active,createdAt,updatedAt FROM users ORDER BY createdAt DESC').all(); const form=`<h2>Create user</h2><form method="post" action="/owner/users" class="form-grid"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Role<select name="role"><option value="manager">Cart Manager</option><option value="owner">Owner/Admin</option></select></label><label>Temporary password<input name="password" type="password" minlength="8" required></label><button class="primary">Create user</button></form>`; const table=`<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Active</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.email)}</td><td>${r.role}</td><td><span class="badge ${r.active?'ok':'danger'}">${r.active?'Active':'Inactive'}</span></td><td>${r.updatedAt}</td><td><form method="post" action="/owner/users/${r.id}/toggle"><button class="btn secondary">${r.active?'Deactivate':'Activate'}</button></form></td></tr>`).join('')}</tbody></table>`; render(req,res,'table-page',{title:'User Management',form,table}); });
app.post('/owner/users', requireRole('owner'), (req,res)=>{ try{ const b=z.object({name:z.string().min(1),email:z.string().email(),role:z.enum(['owner','manager']),password:z.string().min(8)}).parse(req.body); db.prepare('INSERT INTO users (name,email,passwordHash,role) VALUES (?,?,?,?)').run(b.name,b.email,bcrypt.hashSync(b.password,12),b.role); redirectWith(res,'/owner/users','ok','User created'); } catch(e){ redirectWith(res,'/owner/users','err', e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Duplicate email is not allowed':'Invalid user data'); }});
app.post('/owner/users/:id/toggle', requireRole('owner'), (req,res)=>{ db.prepare('UPDATE users SET active=CASE active WHEN 1 THEN 0 ELSE 1 END, updatedAt=CURRENT_TIMESTAMP WHERE id=?').run(req.params.id); redirectWith(res,'/owner/users','ok','User status updated'); });

app.get('/owner/reports', requireRole('owner'), (req,res)=>{ const range=dateRange(req.query); const rep=reports(range); const intro=`<form class="card form-grid" method="get"><label>From<input type="date" name="from" value="${range.fromDate}"></label><label>To<input type="date" name="to" value="${range.toDate}"></label><button class="primary">Apply</button><a class="btn secondary" href="/owner/reports.csv?from=${range.fromDate}&to=${range.toDate}">Export CSV</a></form><section class="grid stats"><article class="card stat"><span>Gross sales</span><strong>₹${money(rep.totals.gross)}</strong></article><article class="card stat"><span>Returns</span><strong>₹${money(rep.totals.returns)}</strong></article><article class="card stat"><span>Net sales</span><strong>₹${money(rep.totals.net)}</strong></article><article class="card stat"><span>Pieces</span><strong>${rep.totals.pieces}</strong></article></section>`; const table=`<table><thead><tr><th>Date/time</th><th>Bill</th><th>Manager</th><th>Type</th><th>Item ID</th><th>Item</th><th>Qty</th><th>MRP</th><th>Free</th><th>Line</th><th>Cash</th><th>Online</th><th>Remark</th></tr></thead><tbody>${rep.rows.map(r=>`<tr><td>${r.createdAt}</td><td>${r.billNumber}</td><td>${esc(r.managerName)}</td><td>${r.type}</td><td>${r.itemCode}</td><td>${esc(r.itemName)}</td><td>${r.quantity}</td><td>₹${money(r.mrp)}</td><td>${r.isFree?'Yes':'No'}</td><td>₹${money(r.lineTotal)}</td><td>₹${money(r.cashAmount)}</td><td>₹${money(r.onlineAmount)}</td><td>${esc(r.remark||'')}</td></tr>`).join('') || '<tr><td colspan="13" class="empty">Empty report result</td></tr>'}</tbody></table>`; render(req,res,'table-page',{title:'Sales Reports',intro,table}); });
app.get('/owner/reports.csv', requireRole('owner'), (req,res)=>{ const range=dateRange(req.query); const rep=reports(range); const csv=stringify(rep.rows.map(r=>({'Date/time':r.createdAt,'Bill ID':r.billNumber,'Manager name':r.managerName,'Type':r.type,'Item ID':r.itemCode,'Item name':r.itemName,'Quantity':r.quantity,'MRP':r.mrp,'Free item flag':r.isFree?'yes':'no','Line total':r.lineTotal,'Cash amount':r.cashAmount,'Online amount':r.onlineAmount,'Bill total':r.totalAmount,'Remarks':r.remark||'','Return reference':r.originalSaleItemId||''})),{header:true}); res.setHeader('Content-Type','text/csv'); res.setHeader('Content-Disposition',`attachment; filename="sales-report-${range.fromDate}-to-${range.toDate}.csv"`); res.send(csv); });

app.get('/manager', requireRole('manager'), (req,res)=>{ const s=todaySummary(req.user.id); const intro=`<section class="grid stats"><article class="card stat"><span>Today’s pieces sold</span><strong>${s.pieces}</strong></article><article class="card stat"><span>Today’s sales amount</span><strong>₹${money(s.total)}</strong></article><article class="card stat"><span>Cash amount</span><strong>₹${money(s.cash)}</strong></article><article class="card stat"><span>Online amount</span><strong>₹${money(s.online)}</strong></article></section><section class="grid two"><a class="card" href="/manager/pos"><h2>POS Billing</h2><p>Start a new customer bill.</p></a><a class="card" href="/manager/returns"><h2>Returns</h2><p>Return today’s own sale lines.</p></a><a class="card" href="/manager/stock"><h2>Available Stock</h2><p>View fridge stock and transfer backup stock.</p></a></section>`; render(req,res,'table-page',{title:'Manager Home',intro,table:''}); });
app.get('/manager/stock', requireRole('manager'), (req,res)=>{ const rows=itemRows(true); const table=`<table><thead><tr><th>Item</th><th>Main Fridge</th><th>Second Fridge</th><th>Low stock</th><th>Transfer</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.mainFridgeQty}</td><td>${r.secondFridgeQty}</td><td><span class="badge ${r.mainFridgeQty<=r.lowStockThreshold?'danger':'ok'}">${r.mainFridgeQty<=r.lowStockThreshold?'Warning':'OK'}</span></td><td><form class="actions" method="post" action="/manager/transfer"><input type="hidden" name="itemId" value="${r.id}"><input name="quantity" type="number" min="1" max="${r.secondFridgeQty}" placeholder="pcs"><button class="btn secondary">Transfer</button></form></td></tr>`).join('')}</tbody></table>`; render(req,res,'table-page',{title:'Available Stock',table}); });
app.post('/manager/transfer', requireRole('manager'), (req,res)=>{ try{ db.transaction(()=>{ const qty=int(req.body.quantity || req.body[`transfer_${req.body.itemId}`]); const row=db.prepare(`SELECT i.*, inv.mainFridgeQty, inv.secondFridgeQty FROM items i JOIN inventory inv ON inv.itemId=i.id WHERE i.id=? AND i.active=1 AND i.hidden=0`).get(req.body.itemId); if(!row) throw new Error('Item is inactive'); if(qty<=0) throw new Error('Enter transfer quantity'); if(row.secondFridgeQty<qty) throw new Error('Second Fridge stock is insufficient'); db.prepare('UPDATE inventory SET mainFridgeQty=mainFridgeQty+?, secondFridgeQty=secondFridgeQty-?, updatedAt=CURRENT_TIMESTAMP WHERE itemId=?').run(qty,qty,row.id); db.prepare(`INSERT INTO stock_movements (itemId,movementType,quantityPieces,quantityBoxes,sourceLocation,destinationLocation,notes,createdBy) VALUES (?,?,?,?,?,?,?,?)`).run(row.id,'transfer_second_to_main',qty,qty/row.piecesPerBox,'second_fridge','main_fridge','Manager fridge transfer',req.user.id); })(); redirectWith(res, req.headers.referer?.includes('/pos')?'/manager/pos':'/manager/stock','ok','Stock transferred to Main Fridge'); } catch(e){ redirectWith(res, req.headers.referer?.includes('/pos')?'/manager/pos':'/manager/stock','err',e.message); }});
app.get('/manager/pos', requireRole('manager'), (req,res)=>{ const rows=itemRows(true); const body=`<form method="post" action="/manager/pos" class="pos-grid"><section class="items-grid">${rows.map(r=>`<article class="item-card ${r.mainFridgeQty<=r.lowStockThreshold?'low':''}"><h3>${esc(r.name)}</h3><p>MRP ₹${money(r.mrp)} · Main ${r.mainFridgeQty} pcs · Second ${r.secondFridgeQty} pcs</p><span class="badge ${r.mainFridgeQty<=r.lowStockThreshold?'danger':'ok'}">${r.mainFridgeQty<=r.lowStockThreshold?'Low stock':'Ready'}</span><div class="qty-row"><input name="qty_${r.id}" type="number" min="0" max="${r.mainFridgeQty}" placeholder="Sale qty"><label><input type="checkbox" name="free_${r.id}" value="1"> Free</label></div><div class="qty-row"><input name="transfer_${r.id}" type="number" min="0" max="${r.secondFridgeQty}" placeholder="Transfer pcs"><button formaction="/manager/transfer" name="itemId" value="${r.id}" class="btn secondary">Transfer</button></div></article>`).join('')}</section><aside class="card"><h2>Payment</h2><label>Cash amount<input name="cashAmount" type="number" min="0" step="0.01" value="0"></label><label>Online amount<input name="onlineAmount" type="number" min="0" step="0.01" value="0"></label><label>Bill remark<textarea name="remark" rows="3"></textarea></label><p class="muted">Cash + online must equal the non-free item total. Stock is reduced from Main Fridge only.</p><button class="primary">Save bill</button></aside></form>`; render(req,res,'table-page',{title:'POS Billing',intro:body,table:''}); });
app.post('/manager/pos', requireRole('manager'), (req,res)=>{ try{ db.transaction(()=>{ const rows=itemRows(true); const lines=[]; rows.forEach(r=>{ const qty=int(req.body[`qty_${r.id}`]); if(qty>0){ if(qty>r.mainFridgeQty) throw new Error(`Insufficient Main Fridge stock for ${r.name}`); const isFree=req.body[`free_${r.id}`]?1:0; lines.push({item:r,qty,isFree,lineTotal:isFree?0:qty*r.mrp}); }}); if(!lines.length) throw new Error('Sale rejected: no items are selected'); const total=lines.reduce((a,l)=>a+l.lineTotal,0), cash=number(req.body.cashAmount), online=number(req.body.onlineAmount); if(Math.abs((cash+online)-total)>0.009) throw new Error('Invalid payment amount: cash + online must equal bill total'); const saleId=db.prepare(`INSERT INTO sales (billNumber,managerId,totalAmount,cashAmount,onlineAmount,remark,type) VALUES (?,?,?,?,?,?,?)`).run(makeBillNumber(),req.user.id,total,cash,online,req.body.remark,'sale').lastInsertRowid; lines.forEach(l=>{ const si=db.prepare(`INSERT INTO sale_items (saleId,itemId,quantity,mrp,isFree,lineTotal) VALUES (?,?,?,?,?,?)`).run(saleId,l.item.id,l.qty,l.item.mrp,l.isFree,l.lineTotal).lastInsertRowid; db.prepare('UPDATE inventory SET mainFridgeQty=mainFridgeQty-?, updatedAt=CURRENT_TIMESTAMP WHERE itemId=? AND mainFridgeQty>=?').run(l.qty,l.item.id,l.qty); db.prepare(`INSERT INTO stock_movements (itemId,movementType,quantityPieces,quantityBoxes,sourceLocation,destinationLocation,notes,saleId,saleItemId,createdBy) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(l.item.id,'pos_sale',-l.qty,-l.qty/l.item.piecesPerBox,'main_fridge','customer','POS sale',saleId,si,req.user.id); }); })(); redirectWith(res,'/manager/pos','ok','Bill saved successfully'); } catch(e){ redirectWith(res,'/manager/pos','err',e.message); }});
app.get('/manager/returns', requireRole('manager'), (req,res)=>{ const rows=returnableLines(req.user.id); const table=`<table><thead><tr><th>Bill</th><th>Item</th><th>Sold</th><th>Returned</th><th>Remaining</th><th>Refund/pc</th><th>Return</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.billNumber}</td><td>${esc(r.name)}</td><td>${r.quantity}</td><td>${r.returnedQty}</td><td>${r.quantity-r.returnedQty}</td><td>₹${r.isFree?'0.00':money(r.mrp)}</td><td><form class="actions" method="post" action="/manager/returns"><input type="hidden" name="saleItemId" value="${r.id}"><input name="quantity" type="number" min="1" max="${r.quantity-r.returnedQty}"><button class="btn secondary">Process return</button></form></td></tr>`).join('') || '<tr><td colspan="7" class="empty">No returnable items for your sales today.</td></tr>'}</tbody></table>`; render(req,res,'table-page',{title:'POS Returns',table}); });
app.post('/manager/returns', requireRole('manager'), (req,res)=>{ try{ db.transaction(()=>{ const qty=int(req.body.quantity); if(qty<=0) throw new Error('Reject invalid return request'); const rows=returnableLines(req.user.id); const line=rows.find(r=>String(r.id)===String(req.body.saleItemId)); if(!line) throw new Error('Sale line not found or not returnable today by this manager'); const remaining=line.quantity-line.returnedQty; if(qty>remaining) throw new Error('Return quantity cannot exceed remaining returnable quantity'); const refund=line.isFree?0:qty*line.mrp; const saleId=db.prepare(`INSERT INTO sales (billNumber,managerId,totalAmount,cashAmount,onlineAmount,remark,type,originalSaleId) VALUES (?,?,?,?,?,?,?,?)`).run(makeBillNumber('RET'),req.user.id,-refund,-refund,0,`Return against ${line.billNumber}`,'return',line.saleId).lastInsertRowid; const si=db.prepare(`INSERT INTO sale_items (saleId,itemId,quantity,mrp,isFree,lineTotal,originalSaleItemId) VALUES (?,?,?,?,?,?,?)`).run(saleId,line.itemId,-qty,line.mrp,line.isFree,-refund,line.id).lastInsertRowid; db.prepare('UPDATE inventory SET mainFridgeQty=mainFridgeQty+?, updatedAt=CURRENT_TIMESTAMP WHERE itemId=?').run(qty,line.itemId); db.prepare(`INSERT INTO stock_movements (itemId,movementType,quantityPieces,quantityBoxes,sourceLocation,destinationLocation,notes,saleId,saleItemId,createdBy) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(line.itemId,'return_movement',qty,0,'customer','main_fridge','POS return',saleId,si,req.user.id); })(); redirectWith(res,'/manager/returns','ok','Return processed and stock added to Main Fridge'); } catch(e){ redirectWith(res,'/manager/returns','err',e.message); }});

app.use((err, req, res, next) => { console.error(err); res.status(500).send('Database error or unexpected application error. Please try again.'); });
app.listen(PORT, () => console.log(`Desi Mastaani Matka Kulfi app running on http://localhost:${PORT}`));
